### ISSUE TITLE
Console Spam [CraftTranslateEvent to StructureBoxes]

### ISSUE THREAD

**Issue by yash-mathur** [eirikh1996/StructureBoxes#13]
**Describe the bug**
Console spam [See Below]

**To Reproduce**
Unsure, Sold a structure box of a movecraft ship to a player

**Environment (please complete the following information):**

 - Server software [Paper 1.15.2 version229]

**Other plugins (please complete the following information, must be output of /plugins):**
 AdvancedAchievements, AsyncWorldEdit, AutoBroadcast*, BanManager*, BKCommonLib, Brewery, Cannons, ChestShop, Chunkmaster, Citizens, CitizensCMD, ClearLag, CommandSpy*, CoreArena, CoreProtect, CrateReloaded, CrazyEnchantments, dynmap*, EnjinMinecraftPlugin, EpicRename, Essentials, EssentialsChat, EssentialsSpawn, FastChunkPregenerator, GameAPI, GPS, GPS-Quests, GrapplingHook*, GUIPlus, HeadDatabase*, HolographicDisplays, ID-Library, LibsDisguises, LightCleaner, LuckPerms, mcMMO, MessageFilter*, MiniaturePets*, mmDisguiseCommand*, Movecraft, Multiverse-Core, MyCommand, MythicMobs, OceanGrow, OneTimeItem, Parrots, PhatLoots, PlaceholderAPI, PluginManager*, ProtectionStones, ProtocolLib, Quests, RandomTeleport, Rankup, SchemBucket*, ServerListPlus*, ServerSigns, ShopGUIPlus, Shopkeepers, SimpleClans, SimplePets, SuperTrailsPro*, TitleManager, TradeMe, UltimateDrugs, Vault, VoxelSniper, WorldBorder, WorldEdit, WorldFiller, WorldGuard, WorldGuardExtraFlags

**Additional context** Console Spam
 Could not pass event CraftTranslateEvent to StructureBoxes v2.1
java.lang.NoSuchMethodError: net.countercraft.movecraft.events.CraftTranslateEvent.getOldHitBox()Lnet/countercraft/movecraft/utils/HashHitBox;
at io.github.eirikh1996.structureboxes.listener.MovecraftListener.onCraftTranslate(MovecraftListener.java:39) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1108.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-229]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-229]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-229]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-229]
at net.countercraft.movecraft.async.translation.TranslationTask.execute(TranslationTask.java:379) ~[?:?]
at net.countercraft.movecraft.async.AsyncTask.run(AsyncTask.java:36) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-229]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-229]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-229]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by eirikh1996** [comment]
You are using an outdated version of Structure Boxes. This is fixed in the latest version: https://dev.bukkit.org/projects/structure-boxes/files/2941208
