### ISSUE TITLE
FastAsyncWorldEdit Compatibility

### ISSUE THREAD

**Issue by ahdg6** [eirikh1996/StructureBoxes#19]
**Environment:**
 - OS: Windows Server 2019
 - Minecraft version 1.16.3
 - Server software [Yatopia](https://github.com/YatopiaMC/Yatopia)

**Structure Boxes can't be loaded on startup**
_logs:_
[00:48:59] [Server thread/ERROR]: Error occurred while enabling StructureBoxes v2.13 (Is it up to date?)
java.lang.NullPointerException: null
	at io.github.eirikh1996.structureboxes.commands.StructureBoxCommand.<init>(StructureBoxCommand.java:38) ~[?:?]
	at io.github.eirikh1996.structureboxes.StructureBoxes.onEnable(StructureBoxes.java:289) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Yatopia-"8a67951"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Yatopia-"8a67951"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Yatopia-"8a67951"]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:487) ~[patched_1.16.3.jar:git-Yatopia-"8a67951"]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:401) ~[patched_1.16.3.jar:git-Yatopia-"8a67951"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:462) ~[patched_1.16.3.jar:git-Yatopia-"8a67951"]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:257) ~[patched_1.16.3.jar:git-Yatopia-"8a67951"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:941) ~[patched_1.16.3.jar:git-Yatopia-"8a67951"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:165) ~[patched_1.16.3.jar:git-Yatopia-"8a67951"]
	at java.lang.Thread.run(Unknown Source) [?:?]
[00:48:59] [Server thread/INFO]: [StructureBoxes] Disabling StructureBoxes v2.13

**Comment by ahdg6** [comment]
It also happens on paper(1.16.3)

**Comment by ahdg6** [comment]
This is confirmed to be the responsibility of FAWE.
Is there any plans to support FAWE?
