### ISSUE TITLE
1.14.4 problems

### ISSUE THREAD

**Issue by TylerS1066** [eirikh1996/StructureBoxes#24]
```
[11:49:57] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v7.0.3;5407315
[...]
[11:49:57] [Server thread/INFO]: [StructureBoxes] Loading StructureBoxes v3.1
[11:49:57] [Server thread/WARN]: java.lang.NoSuchMethodException: com.sk89q.worldguard.bukkit.WorldGuardPlugin.canBuild(org.bukkit.entity.Player, org.bukkit.Location)
[11:49:57] [Server thread/WARN]: 	at java.lang.Class.getDeclaredMethod(Unknown Source)
[11:49:57] [Server thread/WARN]: 	at io.github.eirikh1996.structureboxes.utils.ReflectionUtils.getMethod(ReflectionUtils.java:22)
[11:49:57] [Server thread/WARN]: 	at io.github.eirikh1996.structureboxes.utils.WorldGuardUtils.<clinit>(WorldGuardUtils.java:22)
[11:49:57] [Server thread/WARN]: 	at io.github.eirikh1996.structureboxes.StructureBoxes.onLoad(StructureBoxes.java:110)
[11:49:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355)
[11:49:57] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:202)
[11:49:57] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775)
[11:49:57] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[11:49:57] [Server thread/WARN]: java.lang.NoSuchMethodException: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(org.bukkit.World)
[11:49:57] [Server thread/WARN]: 	at java.lang.Class.getDeclaredMethod(Unknown Source)
[11:49:57] [Server thread/WARN]: 	at io.github.eirikh1996.structureboxes.utils.ReflectionUtils.getMethod(ReflectionUtils.java:22)
[11:49:57] [Server thread/WARN]: 	at io.github.eirikh1996.structureboxes.utils.WorldGuardUtils.<clinit>(WorldGuardUtils.java:23)
[11:49:57] [Server thread/WARN]: 	at io.github.eirikh1996.structureboxes.StructureBoxes.onLoad(StructureBoxes.java:110)
[11:49:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355)
[11:49:57] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:202)
[11:49:57] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775)
[11:49:57] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[11:49:57] [Server thread/WARN]: java.lang.NoSuchMethodException: com.sk89q.worldguard.protection.managers.RegionManager.getApplicableRegions(org.bukkit.Location)
[11:49:57] [Server thread/WARN]: 	at java.lang.Class.getDeclaredMethod(Unknown Source)
[11:49:57] [Server thread/WARN]: 	at io.github.eirikh1996.structureboxes.utils.ReflectionUtils.getMethod(ReflectionUtils.java:22)
[11:49:57] [Server thread/WARN]: 	at io.github.eirikh1996.structureboxes.utils.WorldGuardUtils.<clinit>(WorldGuardUtils.java:24)
[11:49:57] [Server thread/WARN]: 	at io.github.eirikh1996.structureboxes.StructureBoxes.onLoad(StructureBoxes.java:110)
[11:49:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355)
[11:49:57] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:202)
[11:49:57] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775)
[11:49:57] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by TylerS1066** [comment]
More problems in the same log as above:
```
[11:50:07] [Server thread/INFO]: [StructureBoxes] Enabling StructureBoxes v3.1
[11:50:07] [Server thread/INFO]: [StructureBoxes] A compatible version of WorldGuard has been detected
[11:50:07] [Server thread/INFO]: [StructureBoxes] A compatible version of PlotSquared has been detected
[11:50:07] [Server thread/WARN]: java.lang.ClassNotFoundException: com.github.intellectualsites.plotsquared.bukkit.listener.PlayerEvents
[11:50:07] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[11:50:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135)
[11:50:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81)
[11:50:07] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[11:50:07] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[11:50:07] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[11:50:07] [Server thread/WARN]: 	at java.lang.Class.forName(Unknown Source)
[11:50:07] [Server thread/WARN]: 	at io.github.eirikh1996.structureboxes.StructureBoxes.onEnable(StructureBoxes.java:315)
[11:50:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:50:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[11:50:07] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[11:50:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461)
[11:50:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375)
[11:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449)
[11:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266)
[11:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775)
[11:50:07] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[11:50:07] [Server thread/INFO]: [StructureBoxes] Startup - Movecraft detected
```

**Comment by TylerS1066** [comment]
Is this going to be addressed?

**Comment by eirikh1996** [comment]
You are using an outdated version. Most recent is v3.3

**Comment by TylerS1066** [comment]
The initially reported problem still exists in 3.3 on the latest 1.14.4 paper.
