### ISSUE TITLE
1.18.2 Fails to enable, Cannot invoke "java.util.Map.get(Object)"

### ISSUE THREAD

**Issue by TomLewis** [eirikh1996/StructureBoxes#29]
**Describe the bug**
```
[10:32:31] [Server thread/INFO]: [StructureBoxes] Enabling StructureBoxes v3.5
[10:32:31] [Server thread/ERROR]: Error occurred while enabling StructureBoxes v3.5 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "java.util.Map.get(Object)" is null
	at io.github.eirikh1996.structureboxes.StructureBoxes.onEnable(StructureBoxes.java:173) ~[StructureBoxes-Bukkit-3.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:32:31] [Server thread/INFO]: [StructureBoxes] Disabling StructureBoxes v3.5
```

**To Reproduce**
1. Go to Add StructureBoxes 3.5 to PurPur 1.18
2. Start server.

**Environment (please complete the following information):**
 - Minecraft version 1.18 PurPur

**Comment by MrPranklez** [comment]
This issue also occurs on the latest builds of purpur and paper 1.19.4
